emitter:
    emissionAngle: 0.000000
    emissionRange: 100.000000
    emissionVector: [0.000000, 0.000000, 1.000000]
    emissionVectorInverted: true
    name: "sparks"
    shortEffect: false
    size: [0.000000, 0.000000, 0.000000]
    type: "point"
layer0:
    activeLODS: [1, 1, 0, 0]
    alphaOverLife: [0.000000, 1.000000, 0.990000, 0.000000]
    blending: 2
    colorOverLife: [255.000000, 90.000000, 25.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: false
    enableFrameBlend: false
    endTime: 0.100000
    force0: [0.000000, 0.000000, -30.000000]
    forceCount: 1
    forceOverLife0: [0.000000, 1.000000, 1.000000, 0.000000]
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: true
    isLooped: false
    layerType: "particles"
    life: 0.100000
    lifeVariation: 0.200000
    loopEndTime: 4.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "sparks"
    number: 600.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 0.100000
    scaleVelocityFactor: 0.600000
    size: [0.010000, 0.010000]
    sizeVariation: [0.010000, 0.010000]
    sprite: "../../../../../../Data/Gfx/Particles/alpha/Iskr"
    startTime: 0.000000
    type: "layer"
    velocity: 1.000000
    velocityOverLife: [0.000000, 1.000000, 0.093000, 0.560100, 0.996500, 0.507600]
    velocityVariation: 15.000000
