emitter:
    emissionAngle: 0.000000
    emissionRange: 360.000000
    emissionVector: [1.000000, 0.000000, 0.000000]
    emissionVectorInverted: true
    name: "dust"
    radius: 0.500000
    shortEffect: false
    size: [0.000000, 0.000000, 0.000000]
    type: "oncircle"
layer0:
    activeLODS: [0, 1, 0, 0]
    alphaOverLife: [0.000000, 1.000000, 0.990000, 0.000000]
    blending: 1
    colorOverLife: [131.000000, 120.000000, 105.000000, 255.000000]
    degradeStrategy: 2
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.100000
    force0: [0.100000, 0.100000, -0.100000]
    forceCount: 1
    forceOverLife0: [0.000000, 0.000000, 1.000000, 1.000000]
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 5.000000
    loopEndTime: 5.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "dust_shok"
    number: 400.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.750000, 0.750000]
    sizeOverLifeXY: [0.000000, [1.000000, 1.000000], 1.000000, [3.000000, 3.000000]]
    spin: 20.000000
    spinVariation: 10.000000
    sprite: "../../../../../../Data/Gfx/Particles/alpha/explosion_smoke_white"
    startTime: 0.000000
    type: "layer"
    velocity: 0.300000
