emitter:
    emissionAngle: 0.000000
    emissionRange: 0.000000
    emissionVector: [0.000000, 0.000000, 1.000000]
    emissionVectorInverted: true
    name: "foam"
    radius: 0.100000
    shortEffect: false
    size: [0.000000, 0.000000, 0.000000]
    type: "shockwave"
layer0:
    activeLODS: [0, 1, 0, 0]
    alphaOverLife: [0.000000, 0.000000, 0.354700, 0.185400, 0.459300, 0.139700, 0.790700, 0.038800, 0.990000, 0.000000]
    angle: 90.000000
    angleVariation: 90.000000
    blending: 1
    degradeStrategy: 2
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.100000
    force0: [0.000000, 0.000000, 0.100000]
    forceCount: 1
    forceOverLife0: [0.000000, 1.000000, 0.990000, 0.000000]
    frameOverLifeEnabled: false
    frameOverLifeFPS: 6.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 3.000000
    lifeVariation: 1.000000
    loopEndTime: 4.000000
    loopSpriteAnimation: false
    loopVariation: 0.000000
    name: "water3"
    number: 400.000000
    particleOrientation: 8
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 0.000000
    scaleVelocityFactor: 0.000000
    size: [1.000000, 1.000000]
    sizeOverLifeXY: [0.000000, [1.000000, 1.000000], 1.000000, [4.000000, 4.000000]]
    spin: 5.000000
    spinVariation: 5.000000
    sprite: "../../../../../Data/Gfx/Particles/alpha/dust_water"
    startTime: 0.000000
    type: "layer"
    velocity: 8.000000
    velocityOverLife: [0.000000, 1.000000, 0.020000, 0.040000, 0.300000, 0.000000]
