emitter:
    emissionAngle: 118.713600
    emissionRange: 120.000000
    emissionVector: [-0.000000, -0.000000, 1.000000]
    emissionVectorInverted: true
    name: "exp"
    radius: 0.100000
    shortEffect: true
    size: [0.000000, 0.000000, 0.000000]
    type: "point"
layer0:
    activeLODS: [1, 1, 0, 0]
    alphaOverLife: [0.000000, 0.546000, 1.000000, 0.000000]
    angle: 90.000000
    angleVariation: 90.000000
    blending: 3
    colorOverLife: [255.000000, 147.000000, 38.000000, 255.000000]
    degradeStrategy: 2
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: false
    enableFrameBlend: false
    endTime: 0.060000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 60.000000
    inheritPosition: false
    isLong: true
    isLooped: false
    layerType: "particles"
    life: 0.200000
    loopEndTime: 5.000000
    loopSpriteAnimation: false
    loopVariation: 0.000000
    name: "exp"
    number: 1000.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 0.000000
    scaleVelocityFactor: 1.000000
    size: [0.100000, 0.100000]
    sprite: "../../../../../Data/Gfx/Particles/alpha/Iskr_one"
    startTime: 0.000000
    type: "layer"
    velocity: 1.000000
    velocityVariation: 1.500000
