emitter:
    emissionAngle: 0.000000
    emissionRange: 0.000000
    emissionVector: [0.000000, 0.000000, 1.000000]
    emissionVectorInverted: true
    name: "lod"
    shortEffect: false
    size: [0.000000, 0.000000, 0.000000]
    type: "point"
layer0:
    activeLODS: [0, 0, 1, 0]
    alphaOverLife: [0.000000, 0.000000, 0.098200, 0.901800, 0.780700, 0.870200, 1.000000, 0.000000]
    blending: 1
    colorOverLife: [104.000000, 101.000000, 99.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.060000
    force0: [0.000000, 0.000000, -10.000000]
    forceCount: 1
    frameOverLifeEnabled: true
    frameOverLifeFPS: 25.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 4.000000
    loopEndTime: 4.000000
    loopSpriteAnimation: false
    loopVariation: 0.000000
    name: "Lod"
    number: 50.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 0.000000
    scaleVelocityFactor: 0.000000
    size: [1.000000, 1.000000]
    sizeOverLifeXY: [0.000000, [1.258400, 1.258400], 1.000000, [4.000000, 4.000000]]
    sprite: "../../../../../Data/Gfx/Particles/alpha/fog"
    startTime: 0.000000
    type: "layer"
    velocity: 1.000000
    velocityOverLife: [0.000000, 1.000000, 0.147400, 0.094900, 0.990000, 0.000000]
    velocityVariation: 5.000000
