emitter:
    emissionAngle: 0.000000
    emissionRange: 100.000000
    emissionVector: [0.000000, 0.000000, 1.000000]
    emissionVectorInverted: true
    name: "sparks"
    shortEffect: false
    size: [0.000000, 0.000000, 0.000000]
    type: "point"
layer0:
    activeLODS: [1, 1, 1, 0]
    alphaOverLife: 0.200000
    blending: 2
    colorOverLife: [255.000000, 171.000000, 111.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.100000
    force0: [0.000000, 0.000000, -50.000000]
    forceCount: 1
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: true
    isLooped: false
    layerType: "particles"
    life: 1.000000
    lifeVariation: 1.000000
    loopEndTime: 4.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "sparks1"
    number: 1000.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 0.010000
    scaleVelocityFactor: 1.000000
    size: [0.005000, 0.015000]
    sizeVariation: [0.020000, 0.020000]
    sprite: "../../../../../Data/Gfx/Particles/alpha/Iskr_one"
    startTime: 0.000000
    type: "layer"
    velocity: 1.000000
    velocityOverLife: [0.000000, 1.000000, 0.093000, 0.560100, 0.996500, 0.507600]
    velocityVariation: 28.000000
