emitter:
    emissionAngle: 0.000000
    emissionRange: 0.000000
    emissionVector: [0.000000, 0.000000, 1.000000]
    emissionVectorInverted: true
    name: "dust"
    radius: 0.100000
    shortEffect: false
    size: [0.000000, 0.000000, 0.000000]
    type: "shockwave"
layer0:
    activeLODS: [0, 1, 0, 0]
    alphaOverLife: [0.000000, 0.981300, 0.482500, 0.872800, 0.990000, 0.000000]
    angle: 90.000000
    angleVariation: 90.000000
    blending: 1
    colorOverLife: [186.000000, 202.000000, 218.000000, 255.000000]
    degradeStrategy: 2
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.500000
    force0: [0.000000, 0.000000, 0.100000]
    forceCount: 1
    forceOverLife0: [0.000000, 1.000000, 0.990000, 0.000000]
    frameOverLifeEnabled: false
    frameOverLifeFPS: 6.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 3.000000
    lifeVariation: 1.000000
    loopEndTime: 4.000000
    loopSpriteAnimation: false
    loopVariation: 0.000000
    name: "dust3"
    number: 20.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 0.000000
    scaleVelocityFactor: 0.000000
    size: [0.750000, 0.750000]
    sizeOverLifeXY: [0.000000, [1.000000, 1.000000], 1.000000, [4.000000, 4.000000]]
    spin: 20.000000
    spinVariation: 20.000000
    sprite: "../../../../../Data/Gfx/Particles/alpha/explosion_smoke_white"
    startTime: 0.000000
    type: "layer"
    velocity: 8.000000
    velocityOverLife: [0.000000, 1.000000, 0.020000, 0.040000, 0.300000, 0.000000]
