emitter:
    emissionAngle: 118.713600
    emissionRange: 0.000000
    emissionVector: [-0.000000, -0.000000, 1.000000]
    emissionVectorInverted: true
    name: "exp"
    shortEffect: true
    size: [0.000000, 0.000000, 0.000000]
    type: "point"
layer0:
    activeLODS: [1, 1, 1, 0]
    blending: 2
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: false
    enableFrameBlend: false
    endTime: 0.060000
    frameOverLifeEnabled: true
    frameOverLifeFPS: 40.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 0.500000
    loopEndTime: 5.000000
    loopSpriteAnimation: false
    loopVariation: 0.000000
    name: "exp"
    number: 52.691700
    particleOrientation: 1
    pivotPoint: [-0.000000, -0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 0.000000
    scaleVelocityFactor: 0.000000
    size: [0.300000, 0.300000]
    sizeOverLifeXY: [0.000000, [1.000000, 1.000000], 1.000000, [8.000000, 8.000000]]
    sprite: "../../../../../../Data/Gfx/Particles/additive/exp_anim_fire"
    startTime: 0.000000
    type: "layer"
    velocity: 2.000000
